// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqg5HD3sUj-gFI7v5pB6E7Oe-ffoz4KY',
    appId: '1:709340410111:web:1d46eaa9d43f4282c95cca',
    messagingSenderId: '709340410111',
    projectId: 'sdu-event-manager',
    authDomain: 'sdu-event-manager.firebaseapp.com',
    storageBucket: 'sdu-event-manager.firebasestorage.app',
    measurementId: 'G-4606Q32FZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFZOUBS_n1vF_PGoWaekDcsm51FjCuN44',
    appId: '1:709340410111:android:8a9c7d81dd2d335cc95cca',
    messagingSenderId: '709340410111',
    projectId: 'sdu-event-manager',
    storageBucket: 'sdu-event-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmH2S_brsmFWvS7LdZAbYAL0nTl7uviPI',
    appId: '1:709340410111:ios:e4b488b65fef6de5c95cca',
    messagingSenderId: '709340410111',
    projectId: 'sdu-event-manager',
    storageBucket: 'sdu-event-manager.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmH2S_brsmFWvS7LdZAbYAL0nTl7uviPI',
    appId: '1:709340410111:ios:e4b488b65fef6de5c95cca',
    messagingSenderId: '709340410111',
    projectId: 'sdu-event-manager',
    storageBucket: 'sdu-event-manager.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGqg5HD3sUj-gFI7v5pB6E7Oe-ffoz4KY',
    appId: '1:709340410111:web:26b9d17ee1d9fb15c95cca',
    messagingSenderId: '709340410111',
    projectId: 'sdu-event-manager',
    authDomain: 'sdu-event-manager.firebaseapp.com',
    storageBucket: 'sdu-event-manager.firebasestorage.app',
    measurementId: 'G-YY1D2G8ZLG',
  );
}
